wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    huggingface_version: 4.27.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1678962258.862093
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.7.12
      5: 0.14.0
      6: 4.27.1
      8:
      - 5
